# Runs pre-commit hooks on pull requests targeting the main branch

name: Automated Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
          cache: pip

      - name: Create Python virtual environment
        run: "python3 -m venv .venv"

      - name: Install dependencies
        run: |
          bash ./shell_scripts/install_dependencies.sh cli

      - uses: pre-commit/action@v3.0.1
